services:
  demodb-node2:
    image: cockroachdb/cockroach:v25.2.3
    command:
      - start
      - --insecure
      - --join=demodb-node1
      - --listen-addr=0.0.0.0:26257
      - --advertise-addr=demodb-node2:26257
      - --http-addr=0.0.0.0:8088
      - --max-offset=3s
    hostname: demodb-node2
    networks:
      - net_roachnet
    volumes:
      - demodb-data2:/cockroach/cockroach-data
    deploy:
      placement:
        constraints:
          - node.role == manager
  demodb-node3:
    image: cockroachdb/cockroach:v25.2.3
    command:
      - start
      - --insecure
      - --join=demodb-node1
      - --listen-addr=0.0.0.0:26257
      - --advertise-addr=demodb-node3:26257
      - --http-addr=0.0.0.0:8088
      - --max-offset=3s
    hostname: demodb-node3
    networks:
      - net_roachnet
    volumes:
      - demodb-data3:/cockroach/cockroach-data
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  net_roachnet:
    external: true

volumes:
  demodb-data2:
  demodb-data3:

