services:
  mcp-server1:
    build:
      context: .
      dockerfile: local.Dockerfile
      target: full_app
    hostname: mcp-server1
    image: mcp-server:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    command: [
      "uvicorn", "src.main:app",
      "--host", "0.0.0.0", "--port", "8080",
      "--reload",
      "--limit-concurrency", "1000",
      "--log-level", "debug"
    ]
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - net_backend
      - net_roachnet

networks:
  net_backend:
    external: true
  net_roachnet:
    external: true
